version: '3.4'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    hostname: challengedb
    network_mode: "host"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "teste"
    volumes:
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
